/* Paradigm Realm — original game engine, no runtime dependencies. */
(function(root){
'use strict';
const W=48,H=30;
const terrains={ocean:{food:1,prod:0,cost:99},grass:{food:3,prod:1,cost:2},forest:{food:2,prod:2,cost:3},hill:{food:1,prod:3,cost:3},desert:{food:1,prod:1,cost:2},mountain:{food:0,prod:3,cost:99}};
const units={Settler:{cost:35,power:0,moves:4},Worker:{cost:20,power:0,moves:4},Warrior:{cost:18,power:3,moves:4},Scout:{cost:14,power:1,moves:6},Archer:{cost:26,power:5,moves:4,tech:'Archery'},Knight:{cost:40,power:8,moves:6,tech:'Engineering'},Rifleman:{cost:55,power:13,moves:4,tech:'Industry'}};
const techs=[{name:'Agriculture',cost:20,requires:[]},{name:'Archery',cost:25,requires:[]},{name:'Writing',cost:35,requires:['Agriculture']},{name:'Engineering',cost:55,requires:['Writing','Archery']},{name:'Industry',cost:80,requires:['Engineering']},{name:'Electricity',cost:100,requires:['Industry']},{name:'Gate Theory',cost:140,requires:['Electricity']}];
const buildings={Granary:{cost:32,tech:'Agriculture'},Library:{cost:40,tech:'Writing'},Walls:{cost:30,tech:'Engineering'},Gate:{cost:100,tech:'Gate Theory'}};
function rng(seed){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
const dist=(a,b)=>Math.max(Math.abs(a.x-b.x),Math.abs(a.y-b.y));
function create(seed=12345){const r=rng(seed),s={version:1,seed,turn:1,nextId:1,realm:0,selected:null,tech:[],research:'Agriculture',science:0,gold:20,relations:['self','peace','peace'],maps:[],units:[],cities:[],log:[],result:null};
for(let z=0;z<2;z++){const map=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++){const v=Math.sin(x*.21+z)*.55+Math.cos(y*.31)*.45+Math.sin((x+y)*.18)*.3;const n=r();let type=v<-.55||x===0||y===0||x===W-1||y===H-1?'ocean':n<.10?'mountain':n<.25?'hill':n<.45?'forest':n<.56?'desert':'grass';map.push({x,y,z,type,road:false,farm:false,resource:r()<.10?['grain','ore','gold'][Math.floor(r()*3)]:null,seen:false});}s.maps.push(map);}
for(const [owner,x,y] of [[0,10,11],[1,32,9],[2,29,23]]){for(let yy=y-3;yy<=y+3;yy++)for(let xx=x-3;xx<=x+3;xx++)s.maps[0][yy*W+xx].type='grass';addUnit(s,owner,'Settler',x,y,0);addUnit(s,owner,'Warrior',x+1,y,0);addUnit(s,owner,'Worker',x,y+1,0);if(owner)found(s,s.units.find(u=>u.owner===owner&&u.type==='Settler'));}s.selected=s.units.find(u=>u.owner===0).id;reveal(s);log(s,'Your people await a home. Select your Settler and found your first city.');return s;}
function tile(s,x,y,z=0){return x>=0&&y>=0&&x<W&&y<H?s.maps[z][y*W+x]:null;}
function addUnit(s,owner,type,x,y,z){const u={id:s.nextId++,owner,type,x,y,z,hp:10,moves:units[type].moves};s.units.push(u);return u;}
function log(s,msg){s.log.unshift(`Turn ${s.turn}: ${msg}`);s.log=s.log.slice(0,40);}
function reveal(s){for(const a of [...s.units,...s.cities].filter(a=>a.owner===0))for(let y=a.y-3;y<=a.y+3;y++)for(let x=a.x-3;x<=a.x+3;x++){const t=tile(s,x,y,a.z);if(t)t.seen=true;}}
function visible(s,t){return [...s.units,...s.cities].some(a=>a.owner===0&&a.z===t.z&&dist(a,t)<=3);}
function found(s,u){if(!u||u.type!=='Settler'||u.moves<=0)return false;if(s.cities.some(c=>c.z===u.z&&dist(c,u)<4))return false;const c={id:s.nextId++,owner:u.owner,x:u.x,y:u.y,z:u.z,name:['Hearth','Dawnwatch','Stonehaven','Westmarch','New Hope'][s.cities.filter(c=>c.owner===u.owner).length]||'Outpost',pop:1,food:0,production:0,build:'Warrior',buildings:[]};if(u.owner)c.name=(u.owner===1?'Amber':'Azure')+' '+c.name;s.cities.push(c);s.units=s.units.filter(a=>a.id!==u.id);tile(s,c.x,c.y,c.z).road=true;if(!u.owner)log(s,`${c.name} founded.`);reveal(s);check(s);return c;}
function move(s,u,x,y){if(!u||s.result||dist(u,{x,y})!==1)return false;const t=tile(s,x,y,u.z);if(!t||terrains[t.type].cost===99)return false;const cost=t.road&&tile(s,u.x,u.y,u.z).road?1:terrains[t.type].cost;if(u.moves<cost)return false;
const enemy=s.units.find(a=>a.z===u.z&&a.x===x&&a.y===y&&a.owner!==u.owner);const city=s.cities.find(a=>a.z===u.z&&a.x===x&&a.y===y&&a.owner!==u.owner);const target=enemy||city;if(target){if(!units[u.type].power)return false;if((u.owner===0&&s.relations[target.owner]!=='war')||(target.owner===0&&s.relations[u.owner]!=='war'))return false;if(enemy){const defense=units[enemy.type].power+(t.type==='hill'||t.type==='forest'?2:0)+(city?.buildings.includes('Walls')?3:0);const attack=units[u.type].power;enemy.hp-=Math.max(2,Math.round(attack*6/Math.max(1,defense)));u.hp-=Math.max(1,Math.round(defense*4/attack));u.moves=0;s.units=s.units.filter(a=>a.hp>0);if(u.owner===0||enemy.owner===0)log(s,`${u.type} battles ${enemy.type}.`);if(u.hp<=0||enemy.hp>0){check(s);return true;}}if(city){city.owner=u.owner;city.pop=Math.max(1,city.pop-1);log(s,`${city.name} captured.`);}}
u.x=x;u.y=y;u.moves=Math.max(0,u.moves-cost);reveal(s);check(s);return true;}
function available(s){return techs.filter(t=>!s.tech.includes(t.name)&&t.requires.every(n=>s.tech.includes(n)));}
function choices(s,c){return [...Object.keys(units).filter(k=>!units[k].tech||s.tech.includes(units[k].tech)),...Object.keys(buildings).filter(k=>!c.buildings.includes(k)&&s.tech.includes(buildings[k].tech))];}
function yields(s,c){const nearby=[];for(let y=c.y-1;y<=c.y+1;y++)for(let x=c.x-1;x<=c.x+1;x++){const t=tile(s,x,y,c.z);if(t)nearby.push(t);}nearby.sort((a,b)=>(terrains[b.type].food+terrains[b.type].prod+(b.farm?2:0))-(terrains[a.type].food+terrains[a.type].prod+(a.farm?2:0)));let food=2,prod=2;for(const t of nearby.slice(0,c.pop)){food+=terrains[t.type].food+(t.farm?2:0)+(t.resource==='grain'?1:0);prod+=terrains[t.type].prod+(t.resource==='ore'?1:0);}return {food:food-c.pop*2,prod,science:2+c.pop+(c.buildings.includes('Library')?4:0),gold:c.pop};}
function improve(s,u,kind){if(!u||u.type!=='Worker'||u.moves<=0)return false;const t=tile(s,u.x,u.y,u.z);if(kind==='farm'&&(!s.tech.includes('Agriculture')||!['grass','desert'].includes(t.type)))return false;if(!['farm','road'].includes(kind)||t[kind])return false;t[kind]=true;u.moves=0;return true;}
function gate(s,u){if(!u||u.moves<=0)return false;const c=s.cities.find(c=>c.owner===u.owner&&c.z===u.z&&c.x===u.x&&c.y===u.y&&c.buildings.includes('Gate'));if(!c)return false;const z=1-u.z;if(s.units.some(a=>a.z===z&&a.x===u.x&&a.y===u.y&&a.owner!==u.owner))return false;tile(s,u.x,u.y,z).type='grass';u.z=z;u.moves=0;s.realm=z;reveal(s);log(s,'A traveller crosses between realms.');return true;}
function check(s){if(!s.units.some(u=>u.owner===0)&&!s.cities.some(c=>c.owner===0)){s.result='Your civilisation has fallen.';}else if(s.cities.some(c=>c.owner===0&&c.z===1)){s.result='Realm victory! Your civilisation has founded a settlement beyond Earth.';}else if(!s.cities.some(c=>c.owner!==0)&&!s.units.some(u=>u.owner!==0)){s.result='Conquest victory! The world is united.';}}
function endTurn(s){if(s.result)return;s.turn++;for(const c of s.cities){const v=yields(s,c);c.food+=v.food;if(c.food>=12+c.pop*6){c.food=c.buildings.includes('Granary')?Math.floor(c.food/2):0;c.pop++;}c.production+=v.prod;if(c.owner===0){s.science+=v.science;s.gold+=v.gold;}const spec=units[c.build]||buildings[c.build];if(spec&&c.production>=spec.cost){c.production-=spec.cost;if(units[c.build])addUnit(s,c.owner,c.build,c.x,c.y,c.z);else{c.buildings.push(c.build);c.build='Warrior';}if(c.owner===0)log(s,`${c.name} completes production.`);}}
const t=techs.find(t=>t.name===s.research);if(t&&s.science>=t.cost){s.science-=t.cost;s.tech.push(t.name);log(s,`${t.name} discovered.`);s.research=available(s)[0]?.name||null;}
for(const u of s.units){u.moves=units[u.type].moves;u.hp=Math.min(10,u.hp+1);}const r=rng(s.seed+s.turn*99);
for(const u of [...s.units].filter(u=>u.owner)){if(u.type==='Settler'){if(found(s,u))continue;}if(u.type==='Worker'){tile(s,u.x,u.y,u.z).road=true;}
let targets=s.relations[u.owner]==='war'?s.cities.filter(c=>c.owner===0&&c.z===u.z):[];const target=targets.sort((a,b)=>dist(u,a)-dist(u,b))[0];const dirs=[[-1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]];dirs.sort(()=>r()-.5);if(target)dirs.sort((a,b)=>dist({x:u.x+a[0],y:u.y+a[1]},target)-dist({x:u.x+b[0],y:u.y+b[1]},target));for(const [dx,dy]of dirs){if(move(s,u,u.x+dx,u.y+dy))break;}}
for(const c of s.cities.filter(c=>c.owner)){c.build=s.turn%7===0?'Settler':s.units.filter(u=>u.owner===c.owner).length<16?'Warrior':'Settler';}reveal(s);check(s);}
function validSave(s){return s&&s.version===1&&Number.isInteger(s.turn)&&s.turn>0&&Array.isArray(s.maps)&&s.maps.length===2&&s.maps.every(m=>Array.isArray(m)&&m.length===W*H&&m.every(t=>t&&terrains[t.type]))&&Array.isArray(s.units)&&s.units.every(u=>units[u.type]&&Number.isInteger(u.x)&&u.x>=0&&u.x<W&&Number.isInteger(u.y)&&u.y>=0&&u.y<H&&(u.z===0||u.z===1))&&Array.isArray(s.cities)&&s.cities.every(c=>Array.isArray(c.buildings)&&Number.isFinite(c.pop))&&Array.isArray(s.tech)&&Array.isArray(s.relations)&&Array.isArray(s.log);}
root.Realm={W,H,terrains,units,techs,buildings,create,tile,found,move,available,choices,yields,improve,gate,endTurn,visible,validSave,addUnit};if(typeof module!=='undefined')module.exports=root.Realm;
})(typeof globalThis!=='undefined'?globalThis:this);
