'use strict';
const R=Realm,$=id=>document.getElementById(id),canvas=$('map'),ctx=canvas.getContext('2d'),mini=$('minimap').getContext('2d');let s=R.create(Date.now()%1000000),size=32,selectedCity=null;
const colours=['#98dba2','#e6ac66','#78bddc'];
const palettes=[{ocean:'#264d69',grass:'#687d46',forest:'#3c6143',hill:'#8f8460',desert:'#b5a374',mountain:'#687270'},{ocean:'#333457',grass:'#74608b',forest:'#474b71',hill:'#95829f',desert:'#aaa0b3',mountain:'#656b85'}];
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h);}function sprite(t,px,py){const k=size/16;ctx.save();ctx.translate(px,py);ctx.scale(k,k);rect(0,0,16,16,palettes[t.z][t.type]);let seed=t.x*173+t.y*97+t.z;for(let i=0;i<9;i++){seed=(seed*9301+49297)%233280;rect(seed%15,(seed>>5)%15,2,1,t.type==='ocean'?'#37647a':'#ffffff12');}if(t.type==='forest'){for(const [x,y] of [[2,4],[8,2],[6,9]]){rect(x+2,y+4,1,3,'#67513a');rect(x,y+2,5,3,'#223d36');rect(x+1,y,3,3,t.z?'#6e769e':'#2c5039');}}if(t.type==='mountain'||t.type==='hill'){rect(2,10,12,3,'#55594e');rect(4,7,8,4,'#767961');rect(6,4,4,5,'#a1a28b');if(t.type==='mountain'){rect(7,2,2,4,'#dee0c8');rect(6,4,4,1,'#dee0c8');}}if(t.road){rect(0,7,16,3,'#ad9469');rect(7,0,3,16,'#ad9469');rect(0,8,16,1,'#d4bd88');}if(t.farm){rect(2,2,12,12,'#77723a');for(let i=3;i<14;i+=3)rect(i,2,1,12,'#b8ad55');}if(t.resource){rect(11,11,4,4,'#243132');rect(12,12,2,2,t.resource==='grain'?'#e5ce77':t.resource==='gold'?'#ffd75e':'#c8cfce');}ctx.restore();}
function unitSprite(u){const k=size/16;ctx.save();ctx.translate(u.x*size,u.y*size);ctx.scale(k,k);rect(4,3,8,11,'#152426');rect(6,2,4,4,'#eed3a0');rect(5,6,6,5,colours[u.owner]);rect(5,11,2,3,'#d2c4a1');rect(9,11,2,3,'#d2c4a1');if(u.type==='Settler'){rect(2,6,3,5,'#bf9b6e');rect(5,1,6,2,'#bd9b62');}else if(u.type==='Worker'){rect(12,3,1,10,'#d7b580');rect(10,3,5,2,'#b5c1c3');}else{rect(12,3,1,10,'#d8e1dc');rect(2,7,3,4,colours[u.owner]);}rect(3,15,10,1,'#243033');rect(3,15,u.hp,1,u.hp>4?'#8be197':'#eb7772');ctx.restore();}
function draw(){canvas.width=R.W*size;canvas.height=R.H*size;for(const t of s.maps[s.realm]){const x=t.x*size,y=t.y*size;if(!t.seen){rect(x,y,size,size,'#0e1b25');continue;}sprite(t,x,y);ctx.strokeStyle='#14242230';ctx.strokeRect(x+.5,y+.5,size,size);if(!R.visible(s,t))rect(x,y,size,size,'#07101866');}
for(const c of s.cities.filter(c=>c.z===s.realm&&R.tile(s,c.x,c.y,c.z).seen)){let x=c.x*size,y=c.y*size,k=size/16;ctx.save();ctx.translate(x,y);ctx.scale(k,k);rect(2,6,12,8,'#dfcc9f');rect(1,5,14,3,colours[c.owner]);rect(6,9,3,5,'#4b4540');rect(3,2,2,5,'#e4d8ad');rect(5,2,6,2,colours[c.owner]);ctx.restore();ctx.font='bold 10px monospace';ctx.textAlign='center';ctx.fillStyle='#111d22';ctx.fillRect(x-10,y+size, size+20,13);ctx.fillStyle=colours[c.owner];ctx.fillText(c.name+' '+c.pop,x+size/2,y+size+10);}
for(const u of s.units.filter(u=>u.z===s.realm&&(u.owner===0||R.visible(s,R.tile(s,u.x,u.y,u.z))))){unitSprite(u);if(u.id===s.selected){ctx.strokeStyle='#ffedb3';ctx.lineWidth=2;ctx.strokeRect(u.x*size+1,u.y*size+1,size-2,size-2);}}
for(const t of s.maps[s.realm]){mini.fillStyle=t.seen?palettes[t.z][t.type]:'#0d1922';mini.fillRect(t.x*4,t.y*4,4,4);}for(const c of s.cities.filter(c=>c.z===s.realm&&R.tile(s,c.x,c.y,c.z).seen)){mini.fillStyle=colours[c.owner];mini.fillRect(c.x*4,c.y*4,4,4);}}
function button(text,fn,parent){const b=document.createElement('button');b.textContent=text;b.className='action';b.onclick=fn;parent.append(b);return b;}
function focus(a){s.realm=a.z;render();$('viewport').scrollTo({left:a.x*size-$('viewport').clientWidth/2,top:a.y*size-$('viewport').clientHeight/2});}
function current(){return s.units.find(u=>u.id===s.selected&&u.owner===0);}
function notice(t){$('hint').textContent=t;}
function render(){draw();$('stats').textContent=`Turn ${s.turn}  ·  Gold ${s.gold}  ·  ${s.cities.filter(c=>!c.owner).length} cities`;$('realmLabel').textContent='EARTH';$('era').textContent=' • '+(s.tech.includes('Industry')?'Industrial age':s.tech.includes('Engineering')?'Age of kingdoms':'The first age');$('objective').textContent=s.result||'Explore Earth. Build cities. Lead your civilisation.';$('end').disabled=!!s.result;const box=$('selection');box.replaceChildren();const u=current(),c=s.cities.find(c=>c.id===selectedCity&&c.owner===0);const title=document.createElement('h2');title.textContent=c?c.name:u?u.type:'Orders';box.append(title);
if(c){const y=R.yields(s,c);const p=document.createElement('p');p.textContent=`Population ${c.pop} · Food ${y.food>=0?'+':''}${y.food} · Production +${y.prod} · Science +${y.science}`;box.append(p);const sel=document.createElement('select');sel.setAttribute('aria-label','City production');for(const name of R.choices(s,c)){const op=new Option(`${name} (${(R.units[name]||R.buildings[name]).cost})`,name);sel.add(op);}sel.value=c.build;sel.onchange=()=>{c.build=sel.value;render();};box.append(sel);const info=document.createElement('p');info.textContent=`Production: ${c.production}/${(R.units[c.build]||R.buildings[c.build]).cost} · Buildings: ${c.buildings.join(', ')||'none'}`;box.append(info);}
else if(u){const p=document.createElement('p');p.textContent=`Movement ${u.moves}/${R.units[u.type].moves} · Health ${u.hp}/10`;box.append(p);if(u.type==='Settler')button('Found settlement [B]',()=>{const city=R.found(s,u);if(city){selectedCity=city.id;s.selected=null;}else notice('Cities need at least 4 tiles separation and a Settler with movement.');render();},box);if(u.type==='Worker'){button('Build road',()=>{if(!R.improve(s,u,'road'))notice('Road already built, or no movement left.');render();},box);button('Build farm',()=>{if(!R.improve(s,u,'farm'))notice('Needs Agriculture, grass/desert and movement.');render();},box);}button('Rest / skip unit',()=>{u.moves=0;next();},box);}else{const p=document.createElement('p');p.textContent='Select one of your units or settlements on the map.';box.append(p);}
$('research').replaceChildren();for(const t of R.available(s))$('research').add(new Option(t.name,t.name));$('research').value=s.research||'';const t=R.techs.find(t=>t.name===s.research);$('researchTitle').textContent=t?`${t.name} · ${s.science}/${t.cost}`:'All technologies discovered';$('researchBar').max=t?.cost||1;$('researchBar').value=t?s.science:1;$('techList').textContent='Discovered: '+(s.tech.join(' → ')||'none');$('diplomacy').replaceChildren();[1,2].forEach(o=>button(`${o===1?'Amber League':'Azure Dominion'} · ${s.relations[o]} → ${s.relations[o]==='war'?'offer peace':'declare war'}`,()=>{s.relations[o]=s.relations[o]==='war'?'peace':'war';render();},$('diplomacy')));$('cities').replaceChildren();s.cities.filter(c=>!c.owner).forEach(c=>button(`${c.name} · ${c.pop}`,()=>{selectedCity=c.id;s.selected=null;focus(c);},$('cities')));$('log').replaceChildren();for(const line of s.log.slice(0,10)){const p=document.createElement('p');p.textContent=line;$('log').append(p);}}
canvas.onclick=e=>{const b=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-b.left)/size),y=Math.floor((e.clientY-b.top)/size);const u=s.units.find(u=>!u.owner&&u.x===x&&u.y===y&&u.z===s.realm);const c=s.cities.find(c=>!c.owner&&c.x===x&&c.y===y&&c.z===s.realm);if(c&&(selectedCity!==c.id)&&(!u||current()?.id===u.id)){selectedCity=c.id;s.selected=null;}else if(u){s.selected=u.id;selectedCity=null;}else if(current()){if(!R.move(s,current(),x,y))notice('Move one adjacent tile. Check movement, terrain and diplomatic relations.');}render();};
function next(){const list=s.units.filter(u=>!u.owner&&u.moves>0);if(!list.length){notice('All units have moved. End the turn.');return;}s.selected=list[(list.findIndex(u=>u.id===s.selected)+1)%list.length].id;selectedCity=null;focus(current());}
$('next').onclick=next;$('end').onclick=()=>{R.endTurn(s);render();try{localStorage.setItem('paradigm-autosave',JSON.stringify(s));}catch{notice('Autosave unavailable. Use Export save.');}};$('research').onchange=e=>{s.research=e.target.value;render();};function zoom(delta){size=Math.max(20,Math.min(64,size+delta));render();if(current())focus(current());}$('zoomIn').onclick=()=>zoom(4);$('zoomOut').onclick=()=>zoom(-4);$('minimap').onclick=e=>{const b=e.target.getBoundingClientRect();$('viewport').scrollTo({left:(e.clientX-b.left)/b.width*R.W*size-$('viewport').clientWidth/2,top:(e.clientY-b.top)/b.height*R.H*size-$('viewport').clientHeight/2});};
$('save').onclick=()=>{try{localStorage.setItem('paradigm-save',JSON.stringify(s));notice('Game saved in this browser.');}catch{notice('Browser saving unavailable. Use Export save.');}};
function load(raw){try{const data=JSON.parse(raw);if(!R.validSave(data))throw Error();s=data;selectedCity=null;render();if(current())focus(current());notice('Game loaded.');}catch{notice('Could not load this save. Use an Earth-only version 2 save; earlier two-world saves are incompatible.');}}
$('load').onclick=()=>{try{const raw=localStorage.getItem('paradigm-save')||localStorage.getItem('paradigm-autosave');if(raw)load(raw);else notice('No saved game found.');}catch{notice('Browser saving unavailable. Import an exported save.');}};
$('export').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(s)],{type:'application/json'}));a.href=url;a.download=`paradigm-realm-turn-${s.turn}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{if(e.target.files[0])load(await e.target.files[0].text());e.target.value='';};$('new').onclick=()=>{if(confirm('Start a new world? Export or save first to keep this game.')){s=R.create(Date.now()%1000000);selectedCity=null;focus(current());}};$('help').onclick=()=>$('guide').showModal();$('closeGuide').onclick=()=>$('guide').close();document.addEventListener('keydown',e=>{if($('guide').open||['SELECT','INPUT','BUTTON'].includes(e.target.tagName))return;const dirs={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]};if(dirs[e.key]&&current()){e.preventDefault();const u=current(),[dx,dy]=dirs[e.key];R.move(s,u,u.x+dx,u.y+dy);render();}if(e.key==='Tab'){e.preventDefault();next();}if(e.key==='Enter')$('end').click();if(e.key.toLowerCase()==='b'&&current()?.type==='Settler'){const c=R.found(s,current());if(c){s.selected=null;selectedCity=c.id;}render();}});render();focus(current());$('guide').showModal();
